{% set name = "bumpver" %}
{% set version = "2022.1120" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bumpver-{{ version }}.tar.gz
  sha256: ff8ad562a2ed87e862e07683cb68c4b61046679bf155f7a7ebb20b2ea47775cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - click
    - colorama >=0.4
    - lexid
    - pathlib2
    - setuptools >=45.0.0
    - toml

test:
  imports:
    - bumpver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mbarkhau/bumpver
  summary: Bump version numbers in project files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
