{% set name = "bumpver" %}
{% set version = "2024.1130" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bumpver-{{ version }}.tar.gz
  sha256: 74f7ebc294b2240f346e99748cc6f238e57b050999d7428db75d76baf2bf1437

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - lib3to6
  run:
    - python >=3.5
    - click
    - colorama >=0.4
    - lexid
    - lib3to6
    - looseversion
    - pathlib2
    - setuptools >=45.0.0
    - toml

test:
  imports:
    - bumpver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mbarkhau/bumpver
  summary: Bump version numbers in project files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
