{% set name = "bumpver" %}
{% set version = "2025.1131" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bumpver-{{ version }}.tar.gz
  sha256: a35fd2d43a5f65f014035c094866bd3bd6c739606f29fd41246d6ec6e839d3f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - lib3to6
  run:
    - python >={{ python_min }}
    - click
    - colorama >=0.4
    - lexid
    - lib3to6
    - looseversion
    - pathlib2
    - setuptools >=45.0.0
    - toml

test:
  imports:
    - bumpver
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mbarkhau/bumpver
  summary: Bump version numbers in project files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
